### ISSUE TITLE
AttributeError: 'SceneView' object has no attribute 'setScene'

### ISSUE THREAD

**Issue by mikemhenry** [glotzerlab/fresnel-examples#8]
## File name

`03-Interactive-scene-view.ipynb`

## Description

The instructions say: 
>After you change scene properties, call `setScene` to re-render the scene with the changes. For example: change the material color.
And the code in the cell is:
```python
geometry.material.color = fresnel.color.linear([0.8,0.1,0.1])
view.setScene(scene)
```
Which gives us this traceback:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-c73988f46934> in <module>
      1 geometry.material.color = fresnel.color.linear([0.8,0.1,0.1])
----> 2 view.setScene(scene)

AttributeError: 'SceneView' object has no attribute 'setScene'
```

## Can you fix it?

I'd be happy to include the fix as a separate PR or as part of the PR I am currently working on. I do not know what the proper method call is, so please let me know what it needs to be changed to.

**Comment by joaander** [comment]
I think this was fixed when I recently updated all the examples to work with `master`.
